language: go
go:
  - 1.7
before_install:
  - go get -t -v ./...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -v -coverprofile=mux.coverprofile
  - gover
  - goveralls -coverprofile=mux.coverprofile -service=travis-ci
